[tool.poetry]
name = "spelling"
version = "0.1.0"
description = "Learn to Spell App"
authors = ["Thomas Atkins"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
gtts = "^2.5.4"
flask = "^3.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
